Added image handler
josipslavic/cobe-backend pull request #10
Opened 2023-09-07 13:35 UTC by josipslavic

Serves images from a public folder, also added a default image into the public folder that is used for articles that are populated from the NewsAPI that don't have an image.

2023-09-08 05:16 UTC, JCukovic requested changes

2023-09-08 05:16 UTC, JCukovic commented on src/controllers/news.controller.ts
> +        imageUrl: `${process.env.BACKEND_URL}/public/${req.file.filename}`,
what will happen if we restart backend at some point? (Consider scenario where backend is running for a month in live environment, and now we need to push new version of code - let's say some new feature is added. What will happen to these images?)

2023-09-08 08:50 UTC, JCukovic requested changes
One change needed

2023-09-08 11:45 UTC, JCukovic requested changes

2023-09-08 11:45 UTC, JCukovic commented on src/index.ts
> +cloudinary.v2.config({
This is not the place for cloudinary config. Try to find more suitable location

2023-09-08 11:45 UTC, JCukovic commented on src/index.ts
>  mongoose.connect(process.env.MONGO_URI as string);
Same as the comment above, also, why aren't you handling connection errors (at least to know when something went wrong)? How do you know when the db is connected?

2023-09-08 12:22 UTC, JCukovic approved these changes

2023-09-12 07:45 UTC, anteljubic approved these changes
Just remove not needed env variable and you can merge this

2023-09-12 07:45 UTC, anteljubic commented on .env.example
> +BACKEND_URL=http://localhost:3000
This env variable isn't used anywhere so it can be removed

2023-09-12 07:45 UTC, anteljubic commented on readme.md
> +| BACKEND_URL      | URL to the backend's index page | http://localhost:3000                                                                   |
You are not using this, it can be removed

2023-09-12 07:49 UTC, merged