Added error handling middleware
josipslavic/cobe-backend pull request #13
Opened 2023-09-12 09:54 UTC by josipslavic

2023-09-12 11:26 UTC, anteljubic approved these changes

2023-09-13 05:53 UTC, JCukovic requested changes

2023-09-13 05:53 UTC, JCukovic commented on src/controllers/user.controller.ts
> +      const token = jwt.sign(
extract this into separate method/function

2023-09-13 05:53 UTC, JCukovic commented on src/controllers/user.controller.ts
> +      const isPasswordMatching = await compare(
extract this as well

2023-09-13 05:53 UTC, JCukovic commented on src/controllers/user.controller.ts
> +      const token = jwt.sign(
same as first comment, try to reuse logic where you can

2023-09-13 07:58 UTC, JCukovic requested changes

2023-09-13 07:58 UTC, JCukovic commented on src/controllers/comment.controller.ts
> +      return res.status(statusCodes.ok).json({ message: DELETE_SUCCESS });
extract success responses as well

2023-09-13 07:58 UTC, JCukovic commented on src/middleware/errorHandler.ts
> +  console.log('Middleware Error Hadnling');
not sure if this console log is needed - if you think it is just correct the typo

2023-09-13 12:53 UTC, JCukovic requested changes

2023-09-13 12:53 UTC, JCukovic commented on src/controllers/news.controller.ts
> +      return res.status(statusCodes.ok).json(news);
extract all responses not just the one i commented (try to reuse code where you can)

2023-09-14 10:57 UTC, JCukovic approved these changes

2023-09-14 10:58 UTC, merged