Bugfix: fixed front page endpoint
josipslavic/cobe-backend pull request #6
Opened 2023-08-31 10:09 UTC by josipslavic

For loop nikad neće bacit error, ako je dano krivo ime kategorije samo će vratit prazan array. Popravljen je routing jedino.

2023-08-31 11:41 UTC, JCukovic approved these changes

2023-09-01 06:19 UTC, anteljubic requested changes
News service needs changes

2023-09-01 06:19 UTC, anteljubic commented on src/services/news.service.ts
> +    for (const category of newsCategories) {
This should be changed to something that can handle errors

2023-09-01 10:13 UTC, anteljubic commented on src/services/news.service.ts
> +    });
Why are you not await-ing this any more?

2023-09-01 12:23 UTC, anteljubic approved these changes

2023-09-04 05:47 UTC, merged