Added enums and interfaces
josipslavic/cobe-backend pull request #7
Opened 2023-08-31 11:34 UTC by josipslavic

2023-08-31 12:15 UTC, JCukovic commented on src/controllers/news.controller.ts
> +import { INews } from '../interfaces/news';
maybe it would be better to add all types inside file 'types.ts' (optional)

2023-08-31 12:15 UTC, JCukovic commented on src/controllers/news.controller.ts
> +      `https://newsapi.org/v2/everything?q=${req.params.query}&sortBy=publishedAt&apiKey=${process.env.NEWSAPI_KEY}` // TODO: Handle this through some config variables.
Maybe you could use https://www.npmjs.com/package/newsapi instead of making get request with axios

2023-08-31 12:15 UTC, JCukovic commented on src/controllers/news.controller.ts
> +          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Placeholder_view_vector.svg/681px-Placeholder_view_vector.svg.png'; // TODO: We don't want to have external url-s for pictures.
Don't forget to handle this differently (maybe it would be better to skip those articles where some of the mandatory data is missing)

2023-08-31 12:15 UTC, JCukovic commented on src/controllers/news.controller.ts
> +          article.description.length > 20 // TODO: Set default values in one place so you can change them later easily
Don't forget to add this value as constant

2023-08-31 12:15 UTC, JCukovic commented on src/interfaces/comment.ts
> +  commenter: string;
how will you know who commented, what if user changes its name? Suggestion: add userId instead.

2023-09-07 09:33 UTC, josipslavic commented on src/controllers/news.controller.ts
> +      `https://newsapi.org/v2/everything?q=${req.params.query}&sortBy=publishedAt&apiKey=${process.env.NEWSAPI_KEY}` // TODO: Handle this through some config variables.
Can be added in a different branch

2023-09-07 09:36 UTC, josipslavic commented on src/controllers/news.controller.ts
> +          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Placeholder_view_vector.svg/681px-Placeholder_view_vector.svg.png'; // TODO: We don't want to have external url-s for pictures.
This will be handled differently once image serving is implemented in another branch.

2023-09-07 09:55 UTC, anteljubic reviewed
There are few things to check before merge

2023-09-07 09:55 UTC, anteljubic commented on src/enums/userRoles.ts
> +export enum userRoles {
Change naming to PascalCase because models are also like that so to keep it consistent

2023-09-07 09:55 UTC, anteljubic commented on src/models/User.ts
> +      enum: userRoles,
Are you sure this is correct? I see there was an array before, would it compile correctly?

2023-09-07 09:55 UTC, anteljubic commented on src/services/comment.service.ts
> +      .populate(['commenter', 'news']);
It seems like this could be mapped a bit different to not to use strings, can you check it and see if it's possible?

2023-09-07 11:22 UTC, josipslavic commented on src/models/User.ts
> +      enum: userRoles,
Seems to work and compile correctly

2023-09-07 12:00 UTC, JCukovic requested changes

2023-09-07 12:00 UTC, JCukovic commented on src/enums/relations.ts
> +export enum CommentRelations {
Use same naming styles for enums (PascalCase/camelCase/snake_case). Generally PascalCase is used for enums (apply changes in code where needed, it is important to keep it consistent - choose one and stick with it through application)

2023-09-07 12:00 UTC, JCukovic commented on src/models/Comment.ts
> +    [CommentRelations.commenter]: {
I  don't see value in adding enum in this place (as a property name), this is just my personal opinion. For me the way it was before is better.

2023-09-07 12:34 UTC, JCukovic approved these changes

2023-09-07 12:42 UTC, anteljubic approved these changes

2023-09-07 13:23 UTC, merged