Added constants and env variables
josipslavic/cobe-backend pull request #8
Opened 2023-08-31 11:43 UTC by josipslavic

2023-08-31 12:32 UTC, JCukovic commented on src/controllers/news.controller.ts
> +            ? article.description.slice(0, SHORTENED_ARTICLE_MAX_LENGTH) + '...'
add 0 as constant value as well

2023-08-31 12:32 UTC, JCukovic commented on src/controllers/user.controller.ts
> +        expiresIn: process.env.JWT_EXPIRES_IN, // large number for testing
i think this comment can be deleted

2023-08-31 12:32 UTC, JCukovic commented on src/controllers/user.controller.ts
> +      return res.status(401).json({ errors: [INVALID_PASSWORD] });
it would be better to add more generic message when it comes to login, something like: "Invalid password or email" due to security reasons

2023-09-07 08:34 UTC, anteljubic approved these changes

2023-09-07 09:03 UTC, JCukovic requested changes

2023-09-07 09:03 UTC, JCukovic commented on src/controllers/comment.controller.ts
> +      return res
Add all responses into separate file and use them in appropriate places to avoid duplication (as i can see every response has same structure so it can be extracted to simplify code)

2023-09-07 09:06 UTC, josipslavic commented on src/controllers/comment.controller.ts
> +      return res
Will be added in a different branch.

2023-09-07 09:06 UTC, JCukovic approved these changes

2023-09-07 09:08 UTC, merged